name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Build-Test-Push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub or your container registry
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-server:latest .

      # Test the Docker container (optional, add more tests as needed)
      - name: Test Docker Image
        run: |
          docker run --rm -d -p 3000:3000 --name test-server ${{ secrets.DOCKER_USERNAME }}/simple-server:latest
          sleep 5 # Wait for the server to start
          curl -f http://localhost:3000 || (echo "Test failed!" && exit 1)
          docker stop test-server

      # Push the Docker image to DockerHub
      - name: Push Docker Image
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-server:latest
